### ISSUE TITLE
When new date is added

### ISSUE THREAD

**Issue by max-frai** [bumbeishvili/covid19-daily-data#2]
Hello, thank you for the data.
Could you specify, please, when the new date is added into dataset? At 00:00 UTC?

**Comment by bumbeishvili** [comment]
No, unfortunately, since I will be the only person maintaining dataset, data will be added every day, between

 06:00 - 08:00 UTC.

In Worldometer, data update happens around 00:00-02:00 UTC, so this data will have about 4-5 hour lag

I'll be happy to add contributors If they will be able to update data earlier
