### ISSUE TITLE
docs: methodology on data

### ISSUE THREAD

**Issue by Akuukis** [bumbeishvili/covid19-daily-data#4]
Great stuff! I wish I could use your data for my dashboard [Pandemic Estimator](https://pandemic-estimator.net/) but for that I need to clearly track methodology of data tranformations back to authorative source. The concerning points:
- you split total USA across regions: how can I understand when that's done and when (for other countries) regions have reported numbers, so that I can disregard this adjustment and use the country only instead?
- have you made any adjustments to the original data?
- anything else to mention?

**Comment by bumbeishvili** [comment]
> you split the total USA across regions: how can I understand when that's done and when (for other countries) regions have reported numbers so that I can disregard this adjustment and use the country only instead?

As mentioned in the description, Worldometers does not support region-level data. So I just spread country-level data proportionally to the region level. You will need to group data by `Country/Region` field to get reliable data on the country level. Don't forget to round numbers.

At some point, I plan to merge them, but it won't be breaking change, the structure will stay the same

> have you made any adjustments to the original data?
Yes - check this 
https://github.com/bumbeishvili/covid19-daily-data#other-modifications

> anything else to mention?
Yes, as you know some African countries do not have cases registered yet. There may be a time when they will register it, but I won't be automatically added to the dataset. 

For example, if tomorrow South Sudan registers a case, It won't be added tomorrow, because I will need to research loc, lat for it. I am also saving each days data in the misc folder, so once added, historical data will be preserved, so it won't be breaking change

**Comment by bumbeishvili** [comment]
Let me know if you start using this data for your pandemic Estimator, and I will add it in the list of applications mentioned in README file

**Comment by Akuukis** [comment]
I will look into other sources with region-level data first and then come back to you. Thanks for clarification!

**Comment by bumbeishvili** [comment]
Let me know if you find any

**Comment by Akuukis** [comment]
I've settled with coronadatascraper.com, we can close this now.

FYI what I figured out is that everyone converges to either of 2 popular repositories:
- coronadatascraper.com does aggregation across loads of sources, both JHU and many national ones
- https://github.com/ExpDev07/coronavirus-tracker-api are pragmatic about sources and uses only JHU and CSBS

**Comment by bumbeishvili** [comment]
I took a look at both

In the first case could not find all three (cases, deaths, recovered) time series 

In the second case, they issued a warning that recovered data would not be included

Anyway, I think I will stick to this dataset from now on, JHU dataset was very unreliable from the start, I made so many modifications, it's much better to have your own data source
